# Generated by Django 6.0.3 on 2026-04-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=100, verbose_name='Prefixo')),
            ],
            options={
                'verbose_name': 'Rádio',
                'verbose_name_plural': 'Rádios',
            },
        ),
        migrations.CreateModel(
            name='StatusViatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Status de Viatura',
                'verbose_name_plural': 'Status de Viaturas',
            },
        ),
        migrations.CreateModel(
            name='TipoRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Rádio',
                'verbose_name_plural': 'Tipos de Rádio',
            },
        ),
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=100, verbose_name='Prefixo')),
                ('recurso', models.CharField(max_length=255, verbose_name='Recurso')),
                ('radio_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.radio', verbose_name='Rádio')),
            ],
            options={
                'verbose_name': 'Aeronave',
                'verbose_name_plural': 'Aeronaves',
            },
        ),
        migrations.AddField(
            model_name='radio',
            name='tipo_radio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.tiporadio', verbose_name='Tipo de Rádio'),
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=255, verbose_name='Modelo')),
                ('prefixo', models.CharField(max_length=100, verbose_name='Prefixo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_viaturas/', verbose_name='Foto')),
                ('status_viatura_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.statusviatura', verbose_name='Status da Viatura')),
            ],
            options={
                'verbose_name': 'Viatura',
                'verbose_name_plural': 'Viaturas',
            },
        ),
    ]
