# Generated by Django 6.0.3 on 2026-04-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='marca',
            field=models.CharField(default='Viatura', max_length=255, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='viatura',
            name='modelo',
            field=models.CharField(default='Viatura', max_length=255, verbose_name='Modelo'),
        ),
    ]
