# Generated by Django 6.0.3 on 2026-04-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0002_viatura_marca_alter_viatura_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=100, verbose_name='Prefixo')),
            ],
        ),
    ]
