# Generated by Django 6.0.3 on 2026-04-14 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0003_solo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Aeronave',
                'verbose_name_plural': 'Tipos de Aeronaves',
            },
        ),
        migrations.AlterModelOptions(
            name='radio',
            options={'verbose_name': 'Radio', 'verbose_name_plural': 'Radios'},
        ),
        migrations.AlterModelOptions(
            name='solo',
            options={'verbose_name': 'Solo', 'verbose_name_plural': 'Solos'},
        ),
        migrations.RemoveField(
            model_name='solo',
            name='prefixo',
        ),
        migrations.AddField(
            model_name='solo',
            name='tipo',
            field=models.CharField(default=None, max_length=255, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='radio',
            name='prefixo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Prefixo'),
        ),
        migrations.AlterField(
            model_name='radio',
            name='tipo_radio_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.tiporadio', verbose_name='Tipo de Rádio'),
        ),
        migrations.AddField(
            model_name='aeronave',
            name='tipo_aeronave_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.tipoaeronave', verbose_name='Tipo de Aeronave'),
        ),
    ]
