# Generated by Django 6.0.3 on 2026-04-14 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0004_tipoaeronave_alter_radio_options_alter_solo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='tipo_radio_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.tiporadio', verbose_name='Tipo de Radio'),
        ),
    ]
