# Generated by Django 6.0.3 on 2026-04-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0005_alter_radio_tipo_radio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aeronave',
            name='recurso',
        ),
    ]
