# Generated by Django 6.0.3 on 2026-04-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0006_remove_aeronave_recurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronave',
            name='nome',
            field=models.CharField(default='Aeronave', max_length=255, verbose_name='Nome'),
        ),
    ]
