# Generated by Django 6.0.3 on 2026-04-06 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ocorrencia', models.CharField(max_length=255, verbose_name='Tipo de Ocorrência')),
                ('data_ocorrencia', models.DateField(verbose_name='Data da Ocorrência')),
                ('hora_ocorrencia', models.TimeField(verbose_name='Hora da Ocorrência')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('destino', models.CharField(max_length=255, verbose_name='Destino')),
                ('hora_retorno', models.TimeField(blank=True, null=True, verbose_name='Hora de Retorno')),
            ],
            options={
                'verbose_name': 'Voo',
                'verbose_name_plural': 'Voos',
            },
        ),
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=50, verbose_name='Turno')),
                ('horario_inicial', models.DateTimeField(verbose_name='Horário Inicial')),
                ('horario_final', models.DateTimeField(blank=True, null=True, verbose_name='Horário Final')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('aeronave_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.aeronave', verbose_name='Aeronave')),
            ],
            options={
                'verbose_name': 'Apresentação',
                'verbose_name_plural': 'Apresentações',
            },
        ),
    ]
