# Generated by Django 6.0.3 on 2026-04-06 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0001_initial'),
        ('operacional', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='usuarios',
            field=models.ManyToManyField(related_name='apresentacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuários/Guarnição'),
        ),
        migrations.AddField(
            model_name='apresentacao',
            name='viatura_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.viatura', verbose_name='Viatura'),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='apresentacao_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.apresentacao', verbose_name='Apresentação'),
        ),
        migrations.AddField(
            model_name='voo',
            name='aeronave_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frota.aeronave', verbose_name='Aeronave'),
        ),
        migrations.AddField(
            model_name='voo',
            name='apresentacao_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.apresentacao', verbose_name='Apresentação'),
        ),
    ]
