# Generated by Django 6.0.3 on 2026-04-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0003_apresentacao_inserido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='tipo_apresentacao',
            field=models.CharField(choices=[('viatura', 'Viatura'), ('aeronave', 'Aeronave')], default='viatura', max_length=50, verbose_name='Tipo de Apresentação'),
        ),
    ]
