# Generated by Django 6.0.3 on 2026-04-10 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0003_solo'),
        ('operacional', '0004_apresentacao_tipo_apresentacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='apresentacao',
            name='solo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frota.solo', verbose_name='Solo'),
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='tipo_apresentacao',
            field=models.CharField(choices=[('viatura', 'Viatura'), ('aeronave', 'Aeronave'), ('solo', 'Solo')], default='viatura', max_length=50, verbose_name='Tipo de Apresentação'),
        ),
    ]
