# Generated by Django 6.0.3 on 2026-04-14 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0005_alter_radio_tipo_radio_id'),
        ('operacional', '0005_apresentacao_solo_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApresentacaoRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apresentacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.apresentacao', verbose_name='Apresentação')),
                ('radio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frota.radio', verbose_name='Rádio')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Rádio da Apresentação',
                'verbose_name_plural': 'Rádios da Apresentação',
                'unique_together': {('usuario_id', 'apresentacao_id')},
            },
        ),
    ]
