# Generated by Django 6.0.3 on 2026-04-18 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0006_apresentacaoradio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='horario_final',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horário Final'),
        ),
    ]
