# Generated by Django 6.0.3 on 2026-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0007_alter_apresentacao_horario_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='apresentacao_id',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='guarnicoes_id',
            field=models.ManyToManyField(to='operacional.apresentacao', verbose_name='Guarnição'),
        ),
    ]
