# Generated by Django 6.0.3 on 2026-04-22 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacional', '0008_remove_ocorrencia_apresentacao_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtribuicaoDoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atribuicao', models.CharField(max_length=255, verbose_name='Atribuição')),
            ],
            options={
                'verbose_name': 'Atribuição do Serviço',
                'verbose_name_plural': 'Atribuições do Serviço',
            },
        ),
        migrations.CreateModel(
            name='ApresentacaoAtribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apresentacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.apresentacao', verbose_name='Apresentação')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('atribuicao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operacional.atribuicaodoservico', verbose_name='Atribuição')),
            ],
            options={
                'verbose_name': 'Atribuição da Apresentação',
                'verbose_name_plural': 'Atribuições da Apresentação',
            },
        ),
    ]
