# Generated by Django 6.0.3 on 2026-04-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcao',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='role_id',
        ),
        migrations.AddField(
            model_name='funcao',
            name='roles',
            field=models.ManyToManyField(blank=True, to='usuarios.role', verbose_name='Roles da Função'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(blank=True, to='usuarios.role', verbose_name='Roles Pessoais Extras'),
        ),
    ]
