# Generated by Django 6.0.3 on 2026-04-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_funcao_role_id_remove_usuario_role_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcao',
            old_name='nome_funcao',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='orgao',
            old_name='orgao',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='nome',
        ),
    ]
